version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:EKulikova123@db:5432/myapp
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EKulikova123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
